FROM jfloff/alpine-python:3.6

ENV LANG en_US.UTF-8

ADD . /src/

WORKDIR /src/

RUN \
    pip install --upgrade pip; \
    pip install pipenv; \
    pipenv install --system --deploy --verbose;

CMD python -m app