swagger: "2.0"
info:
  version: "0.1.0"
  title: "Olist"
schemes:
- "https"
host: olist-call-recorder.herokuapp.com 
basePath: "/api/v1"
tags:
- name: "callRecord"
  description: "Calls record"
- name: "phoneBill"
  description: "Phone Bill"

paths:
  /call-records:
    post:
      summary: "Create call record"
      tags:
      - "callRecord"
      operationId: "createCallRecord"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        description: "Call Record"
        schema:
          $ref: "#/definitions/CallRecord"
      responses:
        201:
          description: "Call record created with success"
          schema:
            allOf:
              - $ref: "#/definitions/Response"
              - properties:
                  data:
                    $ref: "#/definitions/CallRecord"
        400:
          description: "Invalid data passed"
          schema:
            $ref: "#/definitions/Response"
        422:
          description: "Call record already exists"
          schema:
            $ref: "#/definitions/Response"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Response"
                    
  /phones/{phone_number}/bills:
    get:
      summary: "Get phone bill"
      tags:
      - "phoneBill"
      operationId: "getPhoneBill"
      produces:
      - "application/json"
      parameters:
      - name: "phone_number"
        in: "path"
        description: "The subscriber phone number"
        required: true
        type: string
      - name: "period"
        in: "query"
        description: "The consumption period"
        pattern: '\d{4}-\d{2}'
        type: string
      - name: "page"
        in: "query"
        description: "The page number"
        type: number
      - name: "limit"
        in: "query"
        description: "The number of items per page"
        type: string
      responses:
        200:
          description: "Bill found"
          schema:
            allOf:
            - $ref: "#/definitions/Response"
            - properties:
                data:
                  $ref: "#/definitions/PhoneBill"
        400:
          description: "Invalid data passed"
          schema:
            $ref: "#/definitions/Response"
        404:
          description: "Bill not found"
          schema:
            $ref: "#/definitions/Response"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Response"


definitions:
  Response:
    type: "object"
    properties:
      data:
        type: "object"
      messages:
        type: "array"
        items:
          type: "string"
  
  CallRecord:
    type: "object"
    required: 
    - "call_id"
    - "type"
    - "timestamp"
    properties:
      id:
        type: "string"
      type:
        type: "string"
        enum:
        - "start"
        - "end"
      timestamp:
        type: "number"
      call_id:
        type: "integer"
      source:
        type: "string"
      destination:
        type: "string"
    example: 
      type: start
      timestamp: 1456747200.0
      call_id: 70
      source: "99988526423"
      destination: "9993468278"

  PhoneBill:
    type: "object"
    properties:
      start_date:
        type: "string"
      start_time:
        type: "string"
      duration:
        type: "string"
      destination:
        type: "string"
      price:
        type: "number"
